{% set version = "1.0.1" %}

package:
  name: adjfind
  version: {{ version }}

source:
  url: https://github.com/zwang-geog/AdjFind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 741d68645d598090722052fd6ee05f077a76cc839ef4835653a4bff1462cfc90

build:
  number: 0
  script: |
    cmake -B build -S . ${CMAKE_ARGS}  # [unix]
    cmake -B build -S . %CMAKE_ARGS%  # [win]
    cmake --build build --config Release -j ${CPU_COUNT}  # [unix]
    cmake --build build --config Release -j %CPU_COUNT%  # [win]   
    cmake --install build

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - libgdal-core
    - libboost-devel

test:
  commands:
    - adjfind --help
    - adjfind --version

about:
  home: https://github.com/zwang-geog/AdjFind
  license: MIT
  license_file: LICENSE
  summary: CLI of specialized path finding algorithms related to adjacency/proximity
  description: |
    The command-line tool supports three main modes:
    • Road Segmentation Mode: Determines which service points (e.g., hydrants) are closest to each road segment using network distance, and optionally splits roads into discrete distance categories for service area analysis.
    • Neighboring Points Mode: Identifies the nearest neighboring service points along a road network in each direction, calculating spacing distances between facilities like hydrants for regulatory compliance assessment.
    • Structure Access Mode: Computes shortest unobstructed paths from building corners to road networks, finding the least accessible points on buildings for emergency response planning and fire code compliance.
  doc_url: https://github.com/zwang-geog/AdjFind/blob/master/README.md
  dev_url: https://github.com/zwang-geog/AdjFind

extra:
  recipe-maintainers:
    - zwang-geog
